config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   root 'myevents#index'
   get '/redirect', to: 'myevents#redirect', as: 'redirect'
   get '/callback', to: 'myevents#callback', as: 'callback'
   get '/calendars', to: 'myevents#calendars', as: 'calendars'
   get '/events/:calendar_id', to: 'myevents#events', as: 'events', calendar_id: /[^\/]+/
   get '/myevents/:calendar_id', to: 'myevents#new_event', as: 'new_event', calendar_id: /[^\/]+/
   post '/create_new_event', to: 'myevents#create_new_event', as: 'create_new_event', calendar_id: /[^\/]+/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/myevents_controller.rb
class MyeventsController < ApplicationController

  before_action :authenticate_user! , except: [:index]

  def index

  end

  def redirect
    client = Signet::OAuth2::Client.new(client_options)
    redirect_to client.authorization_uri.to_s
  end

  def callback
    client = Signet::OAuth2::Client.new(client_options)
    client.code = params[:code]

    response = client.fetch_access_token!

    session[:authorization] = response
    redirect_to calendars_url
  end

  def new_event
    @event =  Event.new
    @cal=params[:calendar_id]
  end

  def calendars
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @calendar_list = service.list_calendar_lists
  end

  def events
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @event_list = service.list_events(params[:calendar_id])
  end


  def create_new_event

    @event = Event.create(event_params)

    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])
    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client
    starting_day = params[:event][:start_date]
    ending_day = params[:event][:end_date]
    sum = params[:event][:summary]
    cal_id = params[:event][:cid]
    des = params[:event][:description]


    event = Google::Apis::CalendarV3::Event.new({
                                                  start: Google::Apis::CalendarV3::EventDateTime.new(date: starting_day),
                                                  end: Google::Apis::CalendarV3::EventDateTime.new(date: ending_day),
                                                  description: des,
                                                  summary: sum
                                                })
    service.insert_event('primary', event)
    flash[:notice] = "Event Added Successfully"
    redirect_to events_path('primary')
  end

  private

  def client_options
    {
      client_id: Rails.application.secrets.google_client_id,
      client_secret: Rails.application.secrets.google_client_secret,
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
      redirect_uri: callback_url
    }
  end

  def event_params
    params.require(:event).permit(:summary, :start, :end)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet">
  </head>

  <body>
 <%=render 'shared/navbar' %>
 <%=render 'shared/flash' %>
  <%= yield %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/myevents/calendars.html.erb
<div class="container">
  <h1>Calender Listing</h1>
  <ul>
    <% @calendar_list.items.each do |calendar| %>
      <%if @calendar_list&.items&.last != calendar %>
          <div class="container_in">
            <li><%= calendar.summary %> </li>
            <div class="down">
              <%#=link_to 'Add Event',new_event_path(calendar.id),class: 'btn' %>
              <%=link_to 'View Events',events_path(calendar.id),class: 'btn'%>
            </div>
          </div>
        <%else%>
        <div class="container_in">
          <li><%= calendar.summary %> </li>
          <div class="down">
            <%=link_to 'Add Event',new_event_path(calendar.id),class: 'btn' %>
            <%=link_to 'View Events',events_path(calendar.id),class: 'btn'%>
          </div>
        </div>
        <%end%>
    <% end %>
  </ul>
</div>

app/views/myevents/events.html.erb
<div class="container">
    <h1>Events Listing</h1>
    <% @event_list.items.each do |event| %>
    <div class="container_in">
      <span class=""><%= 'Title' %>:  <%= event.summary %></span>
      <p>Description : <%= event.description%></p>
      <ul>
        <li>Start : <%= event.start.date %></li>
        <li>end : <%= event.end.date%></li>
      </ul>
    </div>
    <%end %>
</div>

app/views/myevents/index.html.erb
<div class="container">
  <% if user_signed_in? %>
    <h1>Welcome</h1>
  <%else %>
    <h1>Sign in</h1>
  <% end %>
</div>

app/views/myevents/new_event.html.erb
<div class="container">
  <div class="card-panel">
      <%= form_for @event, url: '/create_new_event' do |f| %>
       <div class="form-group">
         <%= f.label :summary %>
         <%= f.text_field :summary,placeholder: "Enter event's title", autofocus: true %>
       </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description,placeholder: "Enter your description", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :start_date %>
        <%= f.date_field :start_date,placeholder: "Enter start date", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :end_date %>
        <%= f.date_field :end_date,placeholder: "Enter end date", autofocus: true %>
      </div>

      <% f.hidden_field :cid, value: @cal %>

      <div class="center-align">
        <%=f.submit "Submit" %>
      </div>

    <%end %>
  </div>

</div>

app/views/shared/_flash.html.erb
<div class="msg">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <h5>&copy Hamza Azeem</h5>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <img class="logo" src="https://hrm-production.s3.amazonaws.com/uploads/company/logo/1/4435cc1e29.png" alt="kjkh">
  <nav>
    <ul class="nav-area">
      <% if user_signed_in? %>
        <li> <%=link_to 'Home', root_path %></li>
        <li> <%=link_to('Edit', edit_user_registration_path) %></li>
        <li> <%=link_to 'Events', redirect_path %></li>
        <%else %>
        <div class="on-logout">
          <li> <%=link_to 'Home', root_path %></li>
        </div>
      <% end %>
    </ul>
  </nav>
  <div class="nav-btn">
    <% if user_signed_in? %>
      <%= link_to'Logout', destroy_user_session_path, method: :delete,class: 'btn-area'%>
    <% else %>
      <%= link_to 'Sign Up', new_user_registration_path,class: 'btn-area'%>
      <%= link_to 'Login', new_user_session_path,class: 'btn-area'%>
    <% end %>
  </div>
</header>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>